version: '2'
 
services:

  infodestinations-ms:
    image: jucrodriguezpu/breaktime-destinations:destinations
    command: bundle exec rails s -b 0.0.0.0
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: infodestinations_image_db
      DB_PORT: 3306
      DB_HOST: infodestinations-db
    ports:
      - "3000:3000"
    links:
      - infodestinations-db

  infodestinations-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
      
  eventos-db:
    image: jucrodriguezpu/breaktime-events-db:events-db
    environment:
      MYSQL_DATABASE: Events
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306

  eventos-ms:
    image: alejosebasp/eventos_eventos-ms:latest
    environment:
      NODE_ENV: production
      DATABASE_HOST: eventos-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: Events
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3003:3000"
    depends_on:
      - eventos-db
    restart: on-failure

  login-db:
    image: jucrodriguezpu/breaktime-login-db:login-db
    environment:
      MYSQL_DATABASE: Ident
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - 3308:3306

  login-ms:
    image: alejosebasp/login-ms:final
    environment:
      NODE_ENV: production
      DATABASE_HOST: login-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: Ident
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "4000:4000"
    depends_on:
      - login-db
    restart: on-failure

  notifications-ms:
    container_name: notifications-ms
    image: jucrodriguezpu/breaktime-notifications:notifications
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3002:3000
    links:
      - notifications-db

  notifications-db:
    image: jucrodriguezpu/breaktime-notifications:notifications
    ports:
      - "27017:27017"

  promociones-db:
    image: jucrodriguezpu/breaktime-promos-db:promos-db
    environment:
      MYSQL_DATABASE: Promociones
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - 3309:3306

  promociones-ms:
    image: alejosebasp/promociones-ms:latest
    environment:
      NODE_ENV: production
      DATABASE_HOST: promociones-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: Promociones
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3004:3000"
    depends_on:
      - promociones-db
    restart: on-failure

  breaktime-ldap:
    image: osixia/openldap:1.1.8
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.org"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: breaktime-ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - breaktime-ldap

  api-gateway:
    image: jucrodriguezpu/breaktime-api:api
    container_name: api-gateway
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      # Destinos
      DESTINATIONS_URL: infodestinations-ms
      DESTINATIONS_PORT: '3000'
      DESTINATIONS_ENTRY: 'destinations'
      
      # Eventos
      EVENTS_URL: eventos-ms
      EVENTS_PORT: '3003'
      EVENTS_ENTRY: 'events'
      RESERVATIONS_URL: eventos-ms
      RESERVATIONS_PORT: '3003'
      RESERVATIONS_ENTRY: 'reservations'
      
      # Login
      USERS_URL: login-ms
      USERS_PORT: '4000'
      USERS_ENTRY: 'users'
      PASSENGERS_URL: login-ms
      PASSENGERS_PORT: '4000'
      PASSENGERS_ENTRY: 'passengers'
      CREWS_URL: login-ms
      CREWS_PORT: '4000'
      CREWS_ENTRY: 'crews'

      # Notifications
      NOTIFICATIONS_URL: notifications-ms
      NOTIFICATIONS_PORT: '3002'
      NOTIFICATIONS_ENTRY: 'notifications'
      
      # Promociones
      PROMOCIONES_URL: promociones-ms
      PROMOCIONES_PORT: '3004'
      PROMOCIONES_ENTRY: 'promociones'
      TIENDAS_URL: promociones-ms
      TIENDAS_PORT: '3004'
      TIENDAS_ENTRY: 'tiendas'

      # Servidor LDAP
      LDAP_URL:  login-ms
      LDAP_PORT: '4000'
      LDAP_ENTRYA:  'auth'
      LDAP_ENTRYAa: 'authAdmin'
      LDAP_ENTRYAd: 'add'
      LDAP_ENTRYAda: 'addAdmin'
      LDAP_ENTRYV: 'validate'

    ports:
      - '5000:5000'

  breaktime:
    image: alejosebasp/breaktime:final
    environment:
      NODE_ENV: production
    ports:
      - 3005:3000
